### ISSUE TITLE
Error building Player because scripts had compiler errors

### ISSUE THREAD

**Issue by ZenithVal** [Naraenda/NarasUnityTools#1]
Upon test build or Build & Publish for VRChat, the process fails and the following errors get spit out for DbonePatcher

Assets\DynamicBone\DynamicBonePatcher.cs(14,2): error CS0246: The type or namespace name 'InitializeOnLoadAttribute' could not be found (are you missing a using directive or an assembly reference?)

Assets\DynamicBone\DynamicBonePatcher.cs(14,2): error CS0246: The type or namespace name 'InitializeOnLoad' could not be found (are you missing a using directive or an assembly reference?)

**Comment by Naraenda** [comment]
Sorry for the late response, but it should be safe to remove (the latest version doesn't has the DBPatcher script anymore) since the VRChat SDK already solves this problem.
